# Basics of numpy

In [147]:
import numpy as np

In [148]:
array1 = np.array([[2,1,2,56,12],[12,324,453,5,6]])  # this command will give us the numpy array by taking the list as argument. the list can be 2d , 
                                                     # 1d or any othe dimension the user wants
array2 = np.array([[1,2,3,4,5],[1,2,3,4]])    

In [149]:
np.arange(6) #---- gives a numpy array having elements from 0 to 6 like range function

array([0, 1, 2, 3, 4, 5])

In [150]:
print(array1.shape)  # tells us about the shape od the array like here the array is 2*5 . incase array is not symmetric , it only givesw the number of primary list present like here if 
              # second list is having 4 elements , then the answer will be 2 
print(array2.shape)    

(2, 5)
(2,)


In [151]:
temp = np.array([65,684,21,968,36,5,389,359,2985,3689,65,29,65,66])
temp = temp.reshape(7,2)   #-- the reshape function modifies the given array in the form of n X m array where n and m are arguments of reshape.here n*m should be equal to size of array 
print(temp)                #-- n=number of rows and m=number of columns or number of elements in an array

array([[  65,  684],
       [  21,  968],
       [  36,    5],
       [ 389,  359],
       [2985, 3689],
       [  65,   29],
       [  65,   66]])


In [152]:
array1.dtype # following command gives us the datatype in the numpy array. we can alsoinitilise our dtype by = np.array([1,2.10,3], dtype='int32') . try running this

dtype('int32')

In [153]:
np.zeros((4,6))  # following command gives us empty numpy list . 
                    # the argument is a tuple which can specify the dimension of the array these are float values

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [154]:
np.ones((3,3))  # here we get empty numpy array with value 1 in float like 1.something

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [155]:
np.empty((4,6)) # the difference between np.zero and np.empty is that the value in zeros will be 0 but in empty , they are garbage. in empty ,
                # only memory allocation takes place and not assignment

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [156]:
# these are numpy operations . these can be computed with another numpy arrays also . here execution is happening element by element and not in normal matrix method like in 
# multiplication the elements are multiplies like 2*2 and 56*56 and not according to matrix rules
array1*array1
array1**array1
array1+array1
array1-array1
array1/array1
1/array1 # this will divide each element of numpy array by 1

array([[0.5       , 1.        , 0.5       , 0.01785714, 0.08333333],
       [0.08333333, 0.00308642, 0.00220751, 0.2       , 0.16666667]])

## slicing

In [157]:
arr_temp = array1.copy()  #   here we are using deep copy. if we shallow copy it , changes in numpy array arr_temp will also reflect in array1

In [158]:
arr_temp[1][4]

6

# matrix operations in numpy

In [159]:
a = np.array([[1,2,3],
                [4,5,6]])
print(a.sum(axis=0))                   # 1+4 , 2+5 , 3+6             
print(a.sum(axis=1))                   # 1+2+3 , 4+5+6

array([5, 7, 9])
array([ 6, 15])


In [160]:
b =  np.array([[45,23,34],
                [49,105,0]])

In [161]:
c = b.transpose().copy()  #--- transpose of a matrix

In [162]:
np.dot(a,c)    #--- dot product of two matrices

array([[193, 259],
       [499, 721]])

In [163]:
# to get the available methods in numpy , we can write dir(np)
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [164]:
np.cross(a,b)  #----- cross product of two matrices

array([[  -1,  101,  -67],
       [-630,  294,  175]])

In [165]:
np.sort(b , axis=0) #---- it sorts the array on 0 axis 
np.sort(b , axis=1)  #---- it sorts the array on 1 axis
np.sort(b) #---- it sorts the whole array
#--- if we pass kind='mergesort' , the numpy will use merge sort . example = np.sort(b , axis=0 , kind='mergesort')

array([[ 23,  34,  45],
       [  0,  49, 105]])

# interpreting data using argsort

In [166]:
c = np.array([12,654,5454,851,-55,0])

In [167]:
np.argsort(c) #-- this method will give us the index values of the elements after sorting them

array([4, 5, 0, 1, 3, 2], dtype=int64)

In [168]:
np.sort(c)

array([ -55,    0,   12,  654,  851, 5454])

In [169]:
np.argmax(c) #--- this method will give us the value of index of largest value

2

In [170]:
np.argmin(c) #-- this method will give us the value of index of minimum value

4

In [171]:
temp = np.array([65,684,21,968,36,5,389,359,2985,3689,65,29,65,66,105])
temp = temp.reshape(3,5)
print(temp)

array([[  65,  684,   21,  968,   36],
       [   5,  389,  359, 2985, 3689],
       [  65,   29,   65,   66,  105]])


In [172]:
np.argsort(temp)

array([[2, 4, 0, 1, 3],
       [0, 2, 1, 3, 4],
       [1, 0, 2, 3, 4]], dtype=int64)

In [173]:
np.argsort(temp , axis=0) #-- here it compares column wise elements

array([[1, 2, 0, 2, 0],
       [0, 1, 2, 0, 2],
       [2, 0, 1, 1, 1]], dtype=int64)

In [144]:
np.argsort(temp,axis=1)  #-- here it compares row wise elements

array([[2, 4, 0, 1, 3],
       [0, 2, 1, 3, 4],
       [1, 0, 2, 3, 4]], dtype=int64)